import { useEffect, useState } from 'react';
import { post, request } from './api';

type Profile='wazuh-alerts-jsonl-v1'|'hayabusa-minimal-csv-v1';
type Artifact={artifact_id:string;tool:string;profile:string;profile_label:string;filename:string;upload_sha256:string;size_bytes:number;quality:{accepted:number;rejected:number;duplicates:number;context_only:number;total_rows:number};context_only:boolean;ingested_at_utc:string};
type Finding={finding_id:string;artifact_id:string;tool:string;profile:string;source_position:number;raw_row:string;raw_row_sha256:string;validation_status:string;validation_error?:string;parsed_timestamp_utc?:string|null;original_timestamp?:string|null;host?:string|null;upstream_alert_id?:string|null;upstream_rule_id?:string|null;upstream_rule_title?:string|null;original_severity?:string|number|null;observables?:Record<string,string>;upstream_technique_labels?:string[];duplicate_of?:string|null;interpretation:string};
type Preview={profile:string;filename:string;size_bytes:number;upload_sha256:string;accepted:number;rejected:number;duplicates:number;context_only:number;total_rows:number;sample:{source_position:number;validation_status:string;validation_error?:string|null;finding?:Record<string,unknown>|null;raw_row:string;duplicate:boolean}[];interpretation:string};
type CaseItem={case_id:string;title:string;revision:number};
type Page={items:Finding[];total:number;next_cursor:number|null};

function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

export function ExternalFindings(){
  const [artifacts,setArtifacts]=useState<Artifact[]>([]);const [artifactId,setArtifactId]=useState('');const [findings,setFindings]=useState<Finding[]>([]);const [cases,setCases]=useState<CaseItem[]>([]);const [file,setFile]=useState<File|null>(null);const [profile,setProfile]=useState<Profile>('wazuh-alerts-jsonl-v1');const [preview,setPreview]=useState<Preview|null>(null);const [query,setQuery]=useState('');const [cursor,setCursor]=useState(0);const [next,setNext]=useState<number|null>(null);const [total,setTotal]=useState(0);const [caseId,setCaseId]=useState('');const [note,setNote]=useState('External finding imported as context; validate independently.');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const selected=artifacts.find(item=>item.artifact_id===artifactId)||null;
  async function act(work:()=>Promise<void>){setBusy(true);setError('');try{await work();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  async function refreshArtifacts(select=''){const [artifactPage,casePage]=await Promise.all([request<{items:Artifact[]}>('/external/artifacts?cursor=0&limit=50'),request<{items:CaseItem[]}>('/cases?cursor=0&limit=50')]);setArtifacts(artifactPage.items);setCases(casePage.items);const target=select||artifactId;if(target&&artifactPage.items.some(item=>item.artifact_id===target))setArtifactId(target);else if(artifactPage.items.length)setArtifactId(artifactPage.items[0].artifact_id);}
  async function loadFindings(id:string,offset=0,search=query){const page=await request<Page>(`/external/findings?artifact_id=${encodeURIComponent(id)}&cursor=${offset}&limit=50&query=${encodeURIComponent(search)}`);setFindings(page.items);setTotal(page.total);setNext(page.next_cursor);setCursor(offset);}
  useEffect(()=>{void act(()=>refreshArtifacts());},[]);
  useEffect(()=>{if(artifactId)void act(()=>loadFindings(artifactId));},[artifactId]);
  function formData():FormData{if(!file)throw new Error('Choose a Wazuh JSONL or Hayabusa minimal CSV file');const form=new FormData();form.append('file',file);form.append('profile',profile);return form;}
  async function makePreview(){setPreview(await request<Preview>('/external/preview',{method:'POST',body:formData()}));}
  async function importFile(){if(!preview||!file||preview.upload_sha256.length!==64)throw new Error('Preview this exact file before importing');const result=await request<{artifact:Artifact}>('/external/import',{method:'POST',body:formData()});setPreview(null);setFile(null);await refreshArtifacts(result.artifact.artifact_id);await loadFindings(result.artifact.artifact_id);}
  async function linkCase(finding:Finding){if(!caseId)throw new Error('Choose a case first');const current=await request<{revision:number}>(`/cases/${caseId}`);await post(`/cases/${caseId}/external-findings`,{expected_revision:current.revision,finding_id:finding.finding_id,note,author:'operator'});}
  async function exportCsv(){if(!selected)throw new Error('Choose an imported artifact');const response=await fetch(`/api/external/artifacts/${selected.artifact_id}/export.csv`);if(!response.ok)throw new Error('External CSV export failed');download(await response.blob(),`traceguard-external-${selected.artifact_id}.csv`);}

  return <section id="external-findings" aria-label="External findings and imports">
    <h2>External findings · Wazuh and Hayabusa file imports</h2>
    <p className="notice">Imports remain external context and never become canonical TraceGuard observations, native incidents, stages, or risk inputs. Wazuh alerts are selected alerts, not a complete population. No Wazuh or Hayabusa service is connected.</p>
    <div className="hunt-grid"><div>
      <label>Documented import profile<select aria-label="External import profile" value={profile} onChange={e=>{setProfile(e.target.value as Profile);setPreview(null);}}><option value="wazuh-alerts-jsonl-v1">Wazuh alerts.json JSONL</option><option value="hayabusa-minimal-csv-v1">Hayabusa minimal CSV timeline</option></select></label>
      <label>External alert or timeline file<input aria-label="External finding upload" type="file" accept=".jsonl,.json,.csv" onChange={e=>{setFile(e.target.files?.[0]??null);setPreview(null);}}/></label>
      <p className="muted">UTF-8, maximum 5 MiB and 10,000 rows. No .evtx, Wazuh archives, or arbitrary CSV schemas.</p>
      <button disabled={busy||!file} onClick={()=>void act(makePreview)}>Preview selected source file</button>
      {preview&&<article aria-label="External import preview"><h3>Import quality preview</h3><p>{preview.filename} · {preview.total_rows} rows · SHA-256 <code>{preview.upload_sha256}</code></p><p>{preview.accepted} accepted · {preview.rejected} rejected · {preview.duplicates} duplicates retained · {preview.context_only} context-only rows</p><p>{preview.interpretation}</p>{preview.sample.slice(0,5).map(row=><details key={row.source_position}><summary>Source row {row.source_position} · {row.validation_status}</summary>{row.validation_error&&<p className="error">{row.validation_error}</p>}<pre>{row.raw_row}</pre></details>)}<button disabled={busy||preview.accepted+preview.duplicates===0} onClick={()=>void act(importFile)}>Import reviewed file</button></article>}
    </div><div>
      <label>Saved external artifacts<select value={artifactId} onChange={e=>setArtifactId(e.target.value)}><option value="">Choose imported artifact</option>{artifacts.map(item=><option key={item.artifact_id} value={item.artifact_id}>{item.tool} · {item.filename} · {item.ingested_at_utc}</option>)}</select></label>
      {selected&&<><h3>{selected.tool} · {selected.profile_label}</h3><p>{selected.quality.accepted} accepted · {selected.quality.rejected} rejected · {selected.quality.duplicates} duplicate rows · {selected.quality.context_only} external-context rows of {selected.quality.total_rows}</p><p>Original upload SHA-256 <code>{selected.upload_sha256}</code></p><button disabled={busy} onClick={()=>void act(exportCsv)}>Download formula-safe CSV view</button><p className="muted">Export escaping prefixes spreadsheet formula-leading cells; original upload and row text remain unchanged.</p></>}
      <form onSubmit={e=>{e.preventDefault();if(artifactId)void act(()=>loadFindings(artifactId,0,query));}}><label>Search imported findings<input value={query} maxLength={200} onChange={e=>setQuery(e.target.value)}/></label><button disabled={busy||!artifactId}>Search source rows</button></form>
      <p>{total} matching external rows · 50 per page.</p>{next!==null&&<button disabled={busy} onClick={()=>void act(()=>loadFindings(artifactId,next!))}>Next external rows</button>}{cursor>0&&<button disabled={busy} onClick={()=>void act(()=>loadFindings(artifactId,0))}>First external rows</button>}
      <label>Attach selected external row to case<select value={caseId} onChange={e=>setCaseId(e.target.value)}><option value="">Choose case</option>{cases.map(item=><option key={item.case_id} value={item.case_id}>{item.title} · r{item.revision}</option>)}</select></label><label>Case link note<input value={note} maxLength={1000} onChange={e=>setNote(e.target.value)}/></label>
      {findings.map(item=><article key={item.finding_id}><span className="pill">EXTERNAL · {item.validation_status}</span><p>Source row {item.source_position} · {item.parsed_timestamp_utc??'time unknown; not eligible for time filtering'} · host {item.host??'unknown'}</p><p>{item.upstream_rule_title??item.validation_error??'No mapped rule title'} · severity {item.original_severity??'unknown'}</p><p>Source alert/rule IDs: {item.upstream_alert_id??'none'} / {item.upstream_rule_id??'none'} · row SHA-256 <code>{item.raw_row_sha256}</code></p>{(item.upstream_technique_labels?.length??0)>0&&<p className="notice">Upstream labels attached to this external row: {item.upstream_technique_labels?.join(', ')}. They do not create native ATT&amp;CK mappings.</p>}<details><summary>Inspect retained original row</summary><pre>{item.raw_row}</pre><p>{item.interpretation}</p></details><button disabled={busy||!caseId||item.validation_status==='rejected'} onClick={()=>void act(()=>linkCase(item))}>Attach external context to selected case</button></article>)}
    </div></div>{error&&<p role="alert" className="error">{error}</p>}
  </section>;
}
