import { useEffect, useState } from 'react';
import { post, request } from './api';
import type { Analysis } from './types';

type Indicator={indicator_id:string;type:'ip'|'domain'|'sha256';value:string;normalized_value:string;source:string;source_reference:string;description:string;notes:string;source_confidence:number|null;effective_from_utc:string|null;effective_until_utc:string|null;recorded_at_utc:string;enabled:boolean};
type Collection={collection_id:string;name:string;description:string;provenance:string;source_reference:string;source_claim:string;revision:number;indicators:Indicator[]};
type CollectionPage={items:Collection[];total:number;next_cursor:number|null};
type SourceAssertion={indicator_id:string;source:string;source_reference:string;description:string;source_confidence:number|null;effective_from_utc:string|null;effective_until_utc:string|null;validity_at_event_time:string;recorded_at_utc:string};
type Match={event_id:string;event_time_utc:string;indicator_type:string;indicator_normalized_value:string;match_field:string;observed_value:string;matched_indicator_ids:string[];source_status:string;validity_status:string;source_assertions:SourceAssertion[]};
type MatchResult={match_id:string;collection_id:string;collection_revision:number;analysis_run_id:string;matched_pair_count:number;matched_event_count:number;matches:Match[];result_sha256:string;interpretation:string;knowledge_interpretation:string;cursor:number;next_cursor:number|null;page_count:number};
type MatchHistory=Omit<MatchResult,'matches'|'cursor'|'next_cursor'|'page_count'>;
type CaseList={items:{case_id:string;title:string;revision:number}[]};

const EXAMPLE=JSON.stringify([{type:'ip',value:'192.0.2.10',source:'Local analyst note',source_reference:'case-123#evidence',description:'Synthetic reserved-address assertion',notes:'Operator supplied',enabled:true}],null,2);

export function Intelligence({run,onInspect}:{run:Analysis|null;onInspect:(runId:string,eventId:string)=>void}) {
  const [collections,setCollections]=useState<Collection[]>([]);const [selectedId,setSelectedId]=useState('');const [name,setName]=useState('');const [description,setDescription]=useState('');const [provenance,setProvenance]=useState('');const [sourceReference,setSourceReference]=useState('');const [entriesText,setEntriesText]=useState(EXAMPLE);const [importFile,setImportFile]=useState<File|null>(null);const [importFormat,setImportFormat]=useState<'csv'|'json'>('csv');const [history,setHistory]=useState<MatchHistory[]>([]);const [result,setResult]=useState<MatchResult|null>(null);const [cases,setCases]=useState<CaseList['items']>([]);const [caseId,setCaseId]=useState('');const [bookmarkNote,setBookmarkNote]=useState('Exact local indicator match; analyst context only.');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const selected=collections.find(item=>item.collection_id===selectedId)||null;
  async function act(work:()=>Promise<void>) {setBusy(true);setError('');try{await work();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  async function refreshList() {const [page,casePage]=await Promise.all([request<CollectionPage>('/intelligence/collections?cursor=0&limit=50'),request<CaseList>('/cases?cursor=0&limit=50')]);setCollections(page.items);setCases(casePage.items);if(!selectedId&&page.items.length)setSelectedId(page.items[0].collection_id);}
  useEffect(()=>{void act(refreshList);},[]);
  useEffect(()=>{if(!selected)return;setName(selected.name);setDescription(selected.description);setProvenance(selected.provenance);setSourceReference(selected.source_reference);setEntriesText(JSON.stringify(selected.indicators.map(({indicator_id,type,value,source,source_reference,description,notes,source_confidence,effective_from_utc,effective_until_utc,enabled})=>({indicator_id,type,value,source,source_reference,description,notes,source_confidence,effective_from_utc,effective_until_utc,enabled})),null,2));setResult(null);void act(async()=>{const page=await request<{items:MatchHistory[]}>(`/intelligence/collections/${selected.collection_id}/matches?cursor=0&limit=20`);setHistory(page.items);});},[selected?.collection_id,selected?.revision]);
  function entries():unknown[] {const parsed=JSON.parse(entriesText);if(!Array.isArray(parsed))throw new Error('Indicator JSON must be a list');return parsed;}
  async function createCollection() {const value=await post<Collection>('/intelligence/collections',{name,description,provenance,source_reference:sourceReference,indicators:entries()});setCollections(prev=>[value,...prev.filter(item=>item.collection_id!==value.collection_id)]);setSelectedId(value.collection_id);}
  async function importCollection() {if(!importFile)throw new Error('Choose a CSV or JSON indicator file first');const form=new FormData();form.append('file',importFile);form.append('import_format',importFormat);form.append('name',name);form.append('description',description);form.append('provenance',provenance);form.append('source_reference',sourceReference);const value=await request<Collection>('/intelligence/collections/import',{method:'POST',body:form});setCollections(prev=>[value,...prev.filter(item=>item.collection_id!==value.collection_id)]);setSelectedId(value.collection_id);setImportFile(null);}
  async function saveRevision() {if(!selected)throw new Error('Select a saved collection first');const value=await request<Collection>(`/intelligence/collections/${selected.collection_id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({expected_revision:selected.revision,name,description,provenance,source_reference:sourceReference,indicators:entries()})});setCollections(prev=>prev.map(item=>item.collection_id===value.collection_id?value:item));}
  async function execute() {if(!selected||!run)throw new Error('Select a retained analysis run before matching');const value=await post<MatchResult>(`/intelligence/collections/${selected.collection_id}/match`,{analysis_run_id:run.analysis_run_id,revision:selected.revision});setResult(value);const [page,casePage]=await Promise.all([request<{items:MatchHistory[]}>(`/intelligence/collections/${selected.collection_id}/matches?cursor=0&limit=20`),request<CaseList>('/cases?cursor=0&limit=50')]);setHistory(page.items);setCases(casePage.items);}
  async function openMatch(matchId:string,cursor=0) {const value=await request<MatchResult>(`/intelligence/matches/${matchId}?cursor=${cursor}&limit=50`);setResult(value);}
  async function bookmark(hit:Match) {if(!result||!caseId)throw new Error('Choose a case before bookmarking this observation');const current=await request<{revision:number}>(`/cases/${caseId}`);await post(`/cases/${caseId}/bookmarks`,{expected_revision:current.revision,analysis_run_id:result.analysis_run_id,event_id:hit.event_id,note:bookmarkNote,author:'operator'});}

  return <section id="local-indicators" aria-label="Local indicator intelligence"><h2>Local indicators · exact structured-field matches</h2>
    <p className="muted">Collections are operator-curated and source-attributed. Matching checks only canonical <code>src_ip</code>, <code>dst_ip</code>, <code>domain</code>, and <code>file_hash</code> fields. No DNS, substring, filename, raw-log prose, external feed, or detector-risk enrichment is used.</p>
    <div className="hunt-grid"><div><label>Saved local collections<select value={selectedId} onChange={e=>setSelectedId(e.target.value)}><option value="">New collection</option>{collections.map(item=><option key={item.collection_id} value={item.collection_id}>{item.name} · r{item.revision}</option>)}</select></label>
      <label>Collection name<input value={name} onChange={e=>setName(e.target.value)} maxLength={120}/></label><label>Description<input value={description} onChange={e=>setDescription(e.target.value)} maxLength={1000}/></label><label>How the source was received<input value={provenance} onChange={e=>setProvenance(e.target.value)} maxLength={1000}/></label><label>Collection source reference<input value={sourceReference} onChange={e=>setSourceReference(e.target.value)} maxLength={500}/></label>
      <label>Typed indicator JSON<textarea aria-label="Typed indicator JSON" value={entriesText} onChange={e=>setEntriesText(e.target.value)} rows={12}/></label>
      <button disabled={busy} onClick={()=>void act(createCollection)}>Create local collection</button>{selected&&<button disabled={busy} onClick={()=>void act(saveRevision)}>Save changes as immutable collection revision</button>}
      <fieldset><legend>Import local CSV or JSON (maximum 1 MiB, 1,000 indicators)</legend><label>Indicator file<input aria-label="Indicator import file" type="file" accept=".csv,.json,text/csv,application/json" onChange={e=>setImportFile(e.target.files?.[0]??null)}/></label><label>Import format<select aria-label="Indicator import format" value={importFormat} onChange={e=>setImportFormat(e.target.value as 'csv'|'json')}><option value="csv">CSV</option><option value="json">JSON</option></select></label><button disabled={busy||!importFile} onClick={()=>void act(importCollection)}>Import into new immutable collection</button><p className="muted">CSV headers: type,value,source,source_reference,description; optional notes, source_confidence, effective_from_utc, effective_until_utc, enabled. Imports stay on this device.</p></fieldset>
    </div><div><p>{collections.length} saved collections. Matching uses one explicitly selected retained view; results are persisted separately from incidents.</p>{selected&&<><h3>{selected.name} · revision {selected.revision}</h3><p>{selected.description}</p><p>{selected.provenance} · source {selected.source_reference}</p><p className="muted">{selected.source_claim}</p><details><summary>Normalized typed values and per-indicator provenance</summary><pre>{JSON.stringify(selected.indicators,null,2)}</pre></details></>}
      {run?<p>Selected view: {run.analysis_run_id} · {run.branch_kind||'ordinary'} · cutoff {run.cutoff}</p>:<p>Run analysis to select a retained view.</p>}<button disabled={busy||!run||!selected} onClick={()=>void act(execute)}>Match exact indicators against selected run</button>
      <h3>Saved match runs</h3>{history.map(item=><button key={item.match_id} disabled={busy} onClick={()=>void act(()=>openMatch(item.match_id))}>{item.matched_pair_count} exact pairs · {item.matched_event_count} observations · run {item.analysis_run_id}</button>)}
      {result&&<article><h3>Exact matches · {result.matched_pair_count} pairs / {result.matched_event_count} observations</h3><p>Collection revision {result.collection_revision} · retained run {result.analysis_run_id} · result SHA-256 <code>{result.result_sha256}</code></p><p className="muted">{result.interpretation}</p><p className="notice">{result.knowledge_interpretation}</p>
        <label>Bookmark a match into case<select value={caseId} onChange={e=>setCaseId(e.target.value)}><option value="">Choose case</option>{cases.map(item=><option key={item.case_id} value={item.case_id}>{item.title} · r{item.revision}</option>)}</select></label><label>Bookmark note<input value={bookmarkNote} onChange={e=>setBookmarkNote(e.target.value)} maxLength={1000}/></label>
        {result.matches.map((hit,index)=><article key={`${hit.event_id}-${hit.match_field}-${index}`}><p>Exact {hit.indicator_type} match · observation {hit.event_id} at {hit.event_time_utc} · canonical field <code>{hit.match_field}</code></p><p>Normalized value {hit.indicator_normalized_value} · observed {hit.observed_value}</p><p>Source state: {hit.source_status} · validity at event time: {hit.validity_status}</p>{hit.source_assertions.map(assertion=><p key={assertion.indicator_id}>Source {assertion.source} · {assertion.source_reference} · {assertion.description} · asserted confidence {assertion.source_confidence??'unspecified'} · {assertion.validity_at_event_time} · recorded {assertion.recorded_at_utc}</p>)}<button disabled={busy} onClick={()=>onInspect(result.analysis_run_id,hit.event_id)}>Inspect exact observation and original source rows</button><button disabled={busy||!caseId} onClick={()=>void act(()=>bookmark(hit))}>Bookmark observation in selected case</button></article>)}
        {result.cursor>0&&<button disabled={busy} onClick={()=>void act(()=>openMatch(result.match_id,0))}>First match page</button>}{result.next_cursor!==null&&<button disabled={busy} onClick={()=>void act(()=>openMatch(result.match_id,result.next_cursor!))}>Next match page</button>}
      </article>}
    </div></div>{error&&<p role="alert" className="error">{error}</p>}
  </section>;
}
