import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';

test('final-release workflows keep analyst context separate and export verifiable artifacts', async ({page,request},testInfo) => {
  const failures:string[]=[];page.on('pageerror',error=>failures.push(error.message));
  const suffix=Date.now();const caseTitle=`Release acceptance case ${suffix}`;
  await page.goto('/');
  await page.getByRole('button',{name:'Load positive demo'}).click();
  await page.getByRole('button',{name:'Analyze rules-only'}).click();
  await page.getByRole('button',{name:/Suspected chain/}).click();
  await page.waitForURL(/incident=/);
  const params=new URLSearchParams(new URL(page.url()).search);const runId=params.get('run')!,incidentId=params.get('incident')!;
  const incidentResponse=await request.get(`/api/incidents/${incidentId}`);expect(incidentResponse.ok(),`run=${runId} incident=${incidentId} body=${await incidentResponse.text()}`).toBeTruthy();
  const incident=await incidentResponse.json();expect(incident.stages).toBeDefined();
  const nativeRunResponse=await request.get(`/api/analyses/${runId}`);expect(nativeRunResponse.ok()).toBeTruthy();
  const nativeRunBefore=await nativeRunResponse.json();const nativeIncidentsBefore=await (await request.get(`/api/analyses/${runId}/incidents`)).json();
  const copyId=incident.stages.at(-1).evidence_event_ids[0];

  const cases=page.getByRole('region',{name:'Cases and investigation notes'});
  await cases.getByLabel('Create from selected retained incident').fill(caseTitle);
  await cases.getByRole('button',{name:'Create linked case'}).click();
  await cases.getByLabel('Manual review task').fill('Ask the asset owner');
  await cases.getByRole('button',{name:'Add task'}).click();
  await cases.getByRole('button',{name:'Complete task'}).click();
  await cases.getByLabel('Add note').fill('Human review note; not detector evidence.');
  await cases.getByRole('button',{name:'Save note'}).click();
  await cases.getByLabel('Observation from selected incident').selectOption(copyId);
  await cases.getByLabel('Bookmark note').fill('Verified copy source');
  await cases.getByRole('button',{name:'Bookmark verified source row'}).click();
  await cases.getByLabel('Next status').selectOption('investigating');
  await cases.getByRole('button',{name:'Save case assessment'}).click();
  await cases.getByLabel('Next status').selectOption('resolved');
  await cases.getByRole('button',{name:'Save case assessment'}).click();
  await page.reload();
  const reopenedCases=page.getByRole('region',{name:'Cases and investigation notes'});
  await reopenedCases.getByRole('button',{name:new RegExp(caseTitle)}).click();
  await expect(reopenedCases.getByText('Human review note; not detector evidence.')).toBeVisible();
  await expect(reopenedCases.getByText(/Verified copy source/)).toBeVisible();
  const download=page.waitForEvent('download');await reopenedCases.getByRole('button',{name:'Export JSON and verify'}).click();await download;
  await expect(reopenedCases.getByRole('status')).toContainText('Valid: retained case revision');

  const hunts=page.getByRole('region',{name:'Saved observation hunts'});
  await hunts.getByLabel('New saved hunt name').fill('Release copy hunt');
  await hunts.getByLabel('Canonical action').fill('file_copy_to_usb');
  await hunts.getByRole('button',{name:'Save filter template'}).click();
  await hunts.getByRole('button',{name:'Execute saved query on selected run'}).click();
  await expect(hunts.getByRole('heading',{name:/Hunt matches/})).toBeVisible();
  await expect(hunts.getByText(new RegExp(runId)).first()).toBeVisible();
  await expect(hunts.getByRole('cell',{name:'file_copy_to_usb'})).toBeVisible();
  await hunts.getByRole('button',{name:'Inspect exact observation'}).click();
  await expect(page.getByRole('region',{name:'Raw evidence'}).locator('pre').last()).toContainText('file_copy_to_usb');

  const sigma=page.getByRole('region',{name:'Sigma subset hunt tester'});
  await sigma.getByLabel('Original and local Sigma rules').selectOption('e3405500-bc2a-4cb7-9ed1-000000000006');
  await sigma.getByRole('button',{name:'Run Sigma hunt on selected retained run'}).click();
  await expect(sigma.getByRole('heading',{name:/Hunt matches · 1/})).toBeVisible();
  await expect(sigma.locator('pre').last()).toContainText('destination_type');

  const intelligence=page.getByRole('region',{name:'Local indicator intelligence'});
  await intelligence.getByLabel('Collection name').fill(`Release exact IOC ${suffix}`);
  await intelligence.getByLabel('How the source was received').fill('Operator-provided synthetic fixture');
  await intelligence.getByLabel('Collection source reference').fill('fixture-record-1');
  await intelligence.getByLabel('Typed indicator JSON').fill(JSON.stringify([{type:'ip',value:'192.0.2.10',source:'Local fixture',source_reference:'fixture-record-1#ip',description:'Synthetic reserved documentation address'}],null,2));
  await intelligence.getByRole('button',{name:'Create local collection'}).click();
  await intelligence.getByRole('button',{name:'Match exact indicators against selected run'}).click();
  await expect(intelligence.getByRole('heading',{name:/Exact matches/})).toBeVisible();
  await expect(intelligence.getByText('canonical field dst_ip').first()).toBeVisible();
  const caseList=await (await request.get('/api/cases?cursor=0&limit=50')).json();
  const caseId=caseList.items.find((item:{title:string})=>item.title===caseTitle).case_id;
  await intelligence.getByLabel('Bookmark a match into case').selectOption(caseId);
  const bookmarkResponse=page.waitForResponse(response=>response.url().includes(`/api/cases/${caseId}/bookmarks`)&&response.request().method()==='POST');
  await intelligence.getByRole('button',{name:'Bookmark observation in selected case'}).first().click();
  const savedBookmark=await bookmarkResponse;expect(savedBookmark.ok(),await savedBookmark.text()).toBeTruthy();
  const persistedCase=await (await request.get(`/api/cases/${caseId}`)).json();
  expect(persistedCase.bookmarks.some((item:{note:string})=>item.note==='Exact local indicator match; analyst context only.')).toBeTruthy();

  const attack=page.getByRole('region',{name:'Evidence-linked ATT&CK view'});
  await expect(attack.getByRole('heading',{name:/T1005/})).toBeVisible();
  await expect(attack.getByRole('heading',{name:/T1052\.001/})).toBeVisible();
  const layerDownload=page.waitForEvent('download');await attack.getByRole('button',{name:/Export current-view Navigator/}).click();
  const layerFile=await layerDownload;const layerPath=testInfo.outputPath('navigator-layer.json');await layerFile.saveAs(layerPath);
  const layer=JSON.parse(await readFile(layerPath,'utf8')) as {versions:Record<string,string>;techniques:Array<{techniqueID:string;score:number}>};
  expect(layer.versions.layer).toBe('4.3');expect(layer.techniques.map(item=>item.techniqueID).sort()).toEqual(['T1005','T1052.001']);
  expect(layer.techniques.every(item=>item.score>=1&&item.score<=100)).toBeTruthy();

  const external=page.getByRole('region',{name:'External findings and imports'});
  const upstreamAlert={timestamp:'2026-10-07T08:00:00Z',id:'synthetic-wz-1',rule:{id:'900001',level:7,description:'=HYPERLINK("https://invalid.example","synthetic")',mitre:{id:['T1052.001']}},agent:{id:'001',name:'fixture-host'},data:{srcip:'192.0.2.44'}};
  await external.getByLabel('External finding upload').setInputFiles({name:'alerts.jsonl',mimeType:'application/x-ndjson',buffer:Buffer.from(`${JSON.stringify(upstreamAlert)}\n`)});
  await external.getByRole('button',{name:'Preview selected source file'}).click();
  await expect(external.getByRole('article',{name:'External import preview'})).toContainText('1 accepted');
  await external.getByRole('button',{name:'Import reviewed file'}).click();
  await expect(external.getByText('External alert or timeline file')).toBeVisible();
  await external.getByText('Inspect retained original row').click();
  await expect(external.getByText(/Upstream labels attached to this external row/)).toContainText('T1052.001');
  const csvDownload=page.waitForEvent('download');await external.getByRole('button',{name:'Download formula-safe CSV view'}).click();
  const csvFile=await csvDownload;const csvPath=testInfo.outputPath('external-findings.csv');await csvFile.saveAs(csvPath);
  const csv=await readFile(csvPath,'utf8');expect(csv).toContain("'=HYPERLINK");
  await external.getByLabel('Attach selected external row to case').selectOption(caseId);
  const externalLinkResponse=page.waitForResponse(response=>response.url().includes(`/api/cases/${caseId}/external-findings`)&&response.request().method()==='POST');
  await external.getByRole('button',{name:'Attach external context to selected case'}).click();
  const externalLink=await externalLinkResponse;expect(externalLink.ok(),await externalLink.text()).toBeTruthy();
  const linkedCase=await (await request.get(`/api/cases/${caseId}`)).json();expect(linkedCase.external_findings).toHaveLength(1);
  expect(linkedCase.external_findings[0].finding_id).toBeTruthy();
  const nativeAfter=await (await request.get(`/api/analyses/${runId}`)).json();
  expect(nativeAfter).toEqual(nativeRunBefore);
  expect(await (await request.get(`/api/analyses/${runId}/incidents`)).json()).toEqual(nativeIncidentsBefore);
  const externalCaseExport=await request.get(`/api/cases/${caseId}/export?format=json`);expect(externalCaseExport.ok()).toBeTruthy();
  const exportedCase=await externalCaseExport.json();expect(exportedCase.external_context).toHaveLength(1);
  expect(exportedCase.external_context[0].host).toBe(upstreamAlert.agent.name);
  expect(exportedCase.external_context[0].raw_row_sha256).toMatch(/^[a-f0-9]{64}$/);
  expect(exportedCase.external_context[0]).not.toHaveProperty('raw_row');
  expect(exportedCase.external_context[0]).not.toHaveProperty('raw_fields');

  await page.reload();
  const reopenedExternal=page.getByRole('region',{name:'External findings and imports'});
  await expect(reopenedExternal).toContainText('synthetic-wz-1');
  const reopenedCasePanel=page.getByRole('region',{name:'Cases and investigation notes'});
  await reopenedCasePanel.getByRole('button',{name:new RegExp(caseTitle)}).click();
  const caseDownload=page.waitForEvent('download');await reopenedCasePanel.getByRole('button',{name:'Export JSON and verify'}).click();
  const caseFile=await caseDownload;const casePath=testInfo.outputPath('case-export.json');await caseFile.saveAs(casePath);
  const caseExport=JSON.parse(await readFile(casePath,'utf8')) as {external_context:Array<{finding_id:string}>};
  expect(caseExport.external_context).toHaveLength(1);expect(caseExport.external_context[0].finding_id).toBeTruthy();
  await expect(reopenedCasePanel.getByRole('status')).toContainText('Valid: retained case revision');
  expect(failures).toEqual([]);
});
