import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { spawnSync } from 'node:child_process';

test('real evidence removal, immutable parent, refresh, export and tamper verification', async ({page,request}) => {
  await page.goto('/');
  await page.getByRole('button',{name:'Load positive demo'}).click();
  await page.getByRole('button',{name:'Analyze rules-only'}).click();
  await page.getByRole('button',{name:/Suspected chain/}).click();
  await expect(page).toHaveURL(/incident=/);
  const params=new URLSearchParams(new URL(page.url()).search);
  const parentId=params.get('run')!,incidentId=params.get('incident')!;
  const parent=await (await request.get(`/api/analyses/${parentId}`)).json();
  const incident=await (await request.get(`/api/incidents/${incidentId}`)).json();
  const parentReport=await (await request.get(`/api/incidents/${incidentId}/report`)).json();
  const copyId=incident.stages[2].evidence_event_ids[0];
  await page.getByText('Evidence sensitivity',{exact:true}).click();
  await page.getByLabel(`Exclude transfer observation ${copyId}`).check();
  await page.getByRole('button',{name:'Rerun without selected evidence'}).click();
  const region=page.getByRole('region',{name:'Evidence sensitivity comparison'});
  await expect(region).toBeVisible();
  await expect(region.getByText(/Lost stages: transfer/)).toBeVisible();
  await expect(region.getByText(/partial_observation · heuristic risk 60/)).toBeVisible();
  await expect(page).toHaveURL(/comparison=/);
  const comparisonId=new URL(page.url()).searchParams.get('comparison')!;
  const result=await (await request.get(`/api/sensitivities/${comparisonId}`)).json();
  expect(result.manifest.excluded_event_ids).toEqual([copyId]);
  expect(result.after_candidates.every((i:{stages:{stage_id:string}[]})=>i.stages.every(s=>s.stage_id!=='transfer'))).toBe(true);
  expect(await (await request.get(`/api/analyses/${parentId}`)).json()).toEqual(parent);
  await region.getByRole('button',{name:'Open child candidate and evidence'}).click();
  await expect(page.getByRole('button',{name:'Open transfer evidence'})).toHaveCount(0);
  await expect(page.getByText(/Run kind: evidence_sensitivity/)).toBeVisible();
  await page.reload();
  await expect(region).toBeVisible();
  expect(new URL(page.url()).searchParams.get('run')).toBe(result.manifest.child_run_id);
  await region.getByRole('button',{name:'Return to unchanged parent'}).click();
  await expect(page.getByRole('button',{name:'Open transfer evidence'})).toBeVisible();
  expect(new URL(page.url()).searchParams.get('run')).toBe(parentId);
  const savedReport=await (await request.get(`/api/incidents/${incidentId}/report`)).json();
  savedReport.validation.checked_at_utc=parentReport.validation.checked_at_utc;
  expect(savedReport).toEqual(parentReport);
  const waiting=page.waitForEvent('download');
  await region.getByRole('button',{name:'Download sensitivity comparison'}).click();
  const download=await waiting;
  const file=resolve(`../runtime/phase4a-browser-reports/${download.suggestedFilename()}`);
  await download.saveAs(file);
  const exported=JSON.parse(readFileSync(file,'utf8'));
  expect(exported).toEqual(result);
  expect((await (await request.post('/api/sensitivity-verifications',{data:exported})).json()).valid).toBe(true);
  const command=spawnSync(resolve(process.platform==='win32' ? '../.venv/Scripts/python.exe' : '../.venv/bin/python'),
    ['-m','traceguard.cli','--db',resolve('../runtime/browser-test.sqlite3'),'verify-report',file],{encoding:'utf8'});
  expect(command.status,command.stdout+command.stderr).toBe(0);
  exported.manifest.excluded_event_ids=[];
  expect((await (await request.post('/api/sensitivity-verifications',{data:exported})).json()).valid).toBe(false);
  await page.screenshot({path:resolve(`../runtime/phase4a-browser-reports/${comparisonId}.png`),fullPage:true});
  await region.screenshot({path:resolve(`../runtime/phase4a-browser-reports/${comparisonId}-comparison.png`)});
});

test('sensitivity errors restore controls and empty child has no invented risk', async ({page,request}) => {
  await page.goto('/');
  await page.getByRole('button',{name:'Load positive demo'}).click();
  await page.getByRole('button',{name:'Analyze rules-only'}).click();
  await page.getByRole('button',{name:/Suspected chain/}).click();
  await expect(page).toHaveURL(/incident=/);
  const incidentId=new URL(page.url()).searchParams.get('incident')!;
  const incident=await (await request.get(`/api/incidents/${incidentId}`)).json();
  await page.getByText('Evidence sensitivity',{exact:true}).click();
  await page.getByLabel(`Exclude authentication observation ${incident.stages[0].evidence_event_ids[0]}`).check();
  await page.route('**/api/analyses/*/sensitivity',route=>route.fulfill({status:422,contentType:'application/json',body:JSON.stringify({detail:'Unsupported parent: test failure response'})}));
  await page.getByRole('button',{name:'Rerun without selected evidence'}).click();
  await expect(page.getByRole('alert')).toContainText('Unsupported parent');
  await expect(page.getByRole('button',{name:'Rerun without selected evidence'})).toBeEnabled();
  await page.unroute('**/api/analyses/*/sensitivity');
  await page.getByRole('button',{name:'Rerun without selected evidence'}).click();
  const region=page.getByRole('region',{name:'Evidence sensitivity comparison'});
  await expect(region.getByText(/No complete chain reconstructed from the remaining observations/)).toBeVisible();
  await expect(region.getByText(/No candidate; incident risk unavailable/)).toBeVisible();
  const id=new URL(page.url()).searchParams.get('comparison')!;
  const exported=await (await request.get(`/api/sensitivities/${id}/report`)).json();
  expect(exported.after_candidates).toEqual([]);
  expect((await (await request.post('/api/sensitivity-verifications',{data:exported})).json()).valid).toBe(true);
});
